import bag1 from "./images/bag1.jpg";
import bag2 from "./images/bag2.jpg";
import bag3 from "./images/bag3.jpg";
import bag4 from "./images/bag4.webp";
import bag1_2 from "./images/bag1-2.webp";
import bag2_2 from "./images/bag2-2.jpg";
import bag3_2 from "./images/bag3-2.jpg";
import bag4_2 from "./images/bag4-2.webp";
import cap1 from "./images/cap1.jpg";
import cap2 from "./images/cap2.jpg";
import cap3 from "./images/cap3.jpg";
import cap4 from "./images/cap4.jpg";
import cap1_2 from "./images/cap1-2.jpg";
import cap2_2 from "./images/cap2-2.jpg";
import cap3_2 from "./images/cap3-2.jpg";
import cap4_2 from "./images/cap4-2.jpg";
import mug1 from "./images/mug1.jpg";
import mug1_2 from "./images/mug1-2.jpg";
import mug2 from "./images/mug2.jpg";
import mug2_2 from "./images/mug2-2.avif";
import mug3 from "./images/mug3.jpg";
import mug3_2 from "./images/mug3-2.webp";
import mug4 from "./images/mug1-1.webp";
import mug4_2 from "./images/mug1-2.webp";
import shirt1 from "./images/shirt1.png";
import shirt2 from "./images/shirt2.png";
import shirt3 from "./images/shirt3.png";
import shirt4 from "./images/shirt4.png";
import shirt1_2 from "./images/shirt3.png";
import shirt2_2 from "./images/shirt1.png";
import shirt3_2 from "./images/shirt4.png";
import shirt4_2 from "./images/shirt2.png";

const dataMerch = [
  {
    id: 1,
    name: "Artisan Handmade Mug",
    category: 'mugs',
    image1: mug1,
    image2: mug1_2,
    description: "Official handmade mugs, comepletely metal free and comes in various colors. Decorate your already lucious cake collections with this mug, you're sure to impress everyone!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 12.99,
    rating: 0,
    comment: "",
  },

  {
    id: 2,
    name: "Handmade Nature and Skies Mug",
    category: 'mugs',
    image1: mug2,
    image2: mug2_2,
    description: "Official handmade mugs, comepletely metal free and comes in various colors. Decorate your already lucious cake collections with this mug, you're sure to impress everyone!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 18.75,
    rating: 0,
    comment: "",
  },
  {
    id: 3,
    name: "Handmade Nature and Skies Mug",
    category: 'mugs',
    image1: mug3,
    image2: mug3_2,
    description: "Official handmade mugs, comepletely metal free and comes in various colors. Decorate your already lucious cake collections with this mug, you're sure to impress everyone!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 18.75,
    rating: 0,
    comment: "",
  },
  {
    id: 4,
    name: "He is Risen Pottery Mug",
    category: 'mugs',
    image1: mug4,
    image2: mug4_2,
    description: "Official handmade mugs, comepletely metal free and comes in various colors. Decorate your already lucious cake collections with this mug, you're sure to impress everyone!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 14.49,
    rating: 0,
    comment: "",
  },
  {
    id: 5,
    name: "Custom Hello Kitty Bag",
    category: 'bags',
    image1: bag1,
    image2: bag1_2,
    description: "The reinforced adjustable shoulder strap allows for a comfortable carrying of the bag and the scratch-resistant coating helps the bag stay looking great. Multiple storage compartments will keep you organized and productive all year!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 38.99,
    rating: 0,
    comment: "",
  },
  {
    id: 6,
    name: "Cats and Bears Bag",
    category: 'bags',
    image1: bag2,
    image2: bag2_2,
    description: "The reinforced adjustable shoulder strap allows for a comfortable carrying of the bag and the scratch-resistant coating helps the bag stay looking great. Multiple storage compartments will keep you organized and productive all year!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 31.50,
    rating: 0,
    comment: "",
  },
  {
    id: 7,
    name: "Custom Utility Bag",
    category: 'bags',
    image1: bag3,
    image2: bag3_2,
    description: "The reinforced adjustable shoulder strap allows for a comfortable carrying of the bag and the scratch-resistant coating helps the bag stay looking great. Multiple storage compartments will keep you organized and productive all year!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 32.75,
    rating: 0,
    comment: "",
  },
  {
    id: 8,
    name: "Adorable Lightwear Bag",
    category: 'bags',
    image1: bag4,
    image2: bag4_2,
    description: "The reinforced adjustable shoulder strap allows for a comfortable carrying of the bag and the scratch-resistant coating helps the bag stay looking great. Multiple storage compartments will keep you organized and productive all year!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 28.99,
    rating: 0,
    comment: "",
  },
  {
    id: 9,
    name: "Custom Branded Caps",
    category: 'caps',
    image1: cap1,
    image2: cap1_2,
    description: "Original custom-made, affordable and very comfortable, comes in various sizes and colors. Having such stylish caps as an accessory, there's no getting around it!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 19.99,
    rating: 0,
    comment: "",
  },
  {
    id: 10,
    name: "Custom Branded Caps",
    category: 'caps',
    image1: cap2,
    image2: cap2_2,
    description: "Original custom-made, affordable and very comfortable, comes in various sizes and colors. Having such stylish caps as an accessory, there's no getting around it!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay", 
    price: 18.50,
    rating: 0,
    comment: "",
  },
  {
    id: 11,
    name: "Custom Branded Caps",
    category: 'caps',
    image1: cap3,
    image2: cap3_2,
    description: "Original custom-made, affordable and very comfortable, comes in various sizes and colors. Having such stylish caps as an accessory, there's no getting around it!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 20.49,
    rating: 0,
    comment: "",
  },
  {
    id: 12,
    name: "Custom Branded Caps",
    category: 'caps',
    image1: cap4,
    image2: cap4_2,
    description: "Original custom-made, affordable and very comfortable, comes in various sizes and colors. Having such stylish caps as an accessory, there's no getting around it!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay",
    price: 20.99,
    rating: 0,
    comment: "",
  },
  {
    id: 13,
    name: "Official Blue T-Shirt Customwear Size-XL",
    category: "shirts",
    image1: shirt1,
    image2: shirt1_2,
    description: "Original handmade, official Bakerz Bite-designed T-Shirts! Currently available and in stock on most stores, and in various sizes and colors, get one now!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay", 
    price: 69.99,
    rating: 0,
    comment: "",
  },
  {
    id: 14,
    name: "Official Black T-Shirt Customwear Size-XL",
    category: "shirts",
    image1: shirt2,
    image2: shirt2_2,
    description: "Original handmade, official Bakerz Bite-designed T-Shirts! Currently available and in stock on most stores, and in various sizes and colors, get one now!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay", 
    price: 69.99,
    rating: 0,
    comment: "",
  },
  {
    id: 15,
    name: "Official Black T-Shirt Customwear Size-L",
    category: "shirts",
    image1: shirt3,
    image2: shirt3_2,
    description: "Original handmade, official Bakerz Bite-designed T-Shirts! Currently available and in stock on most stores, and in various sizes and colors, get one now!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay", 
    price: 59.99,
    rating: 0,
    comment: "",
  },
  {
    id: 16,
    name: "Official Blue T-Shirt Customwear Size-L",
    category: "shirts",
    image1: shirt4,
    image2: shirt4_2,
    description: "Original handmade, official Bakerz Bite-designed T-Shirts! Currently available and in stock on most stores, and in various sizes and colors, get one now!",
    content1: "- 100% Original Products.",
    content2: "- Pay on delivery is also available.",
    content3: "- Easy 14 days returns and exchanges.",
    content4: "- 15% Discount using PayPal or ApplePay.",
    content5: "- Comes with discount physical coupon on next purchase.",
    discount: "15% Discount on Paypal or ApplePay", 
    price: 59.99,
    rating: 0,
    comment: "",
  },
];

export default dataMerch;